<?php
require('connect.php');
include('MPDF57/mpdf.php');
date_default_timezone_set('Asia/Calcutta'); 
$time = date('Y-m-d H:i:s');
$po_no=$_GET['po_no'];
$ip = getenv('REMOTE_ADDR');
$userAgent = getenv('HTTP_USER_AGENT');
$referrer = getenv('HTTP_REFERER');
$query = getenv('QUERY_STRING');
$po_no=$_GET['po_no'];
$curYear = date('Y');
$nexYear = date('y')+1;
$n = 0;
$mpdf=new mPDF('c','A4','','',10,10,37,37,5,5); 
$mpdf->mirrorMargins = 1;
$header = '<div align="right"><img src="images/head.jpg" width="126px" /></div>';
$headerE = '<div align="right"><img src="images/head.jpg" width="126px" /></div>';
$footer = '<div align="center"><img src="images/footer.jpg"  /></div>';
$footerE = '<div align="center"><img src="images/footer.jpg"  /></div>';
$mpdf->SetHTMLHeader($header);
$mpdf->SetHTMLFooter($footer);
$result1 = mysql_query("SELECT * FROM  purchase_master where po_no=" .$po_no,$conn);
if($row1 = mysql_fetch_array($result1))
	 {
	$project_id=$row1['project_id'] ;
	$ven_id=$row1['ven_id'];
	$vat_o=$row1['vat'];
	$amounttobepaid=$row1['amounttobepaid'];
	$subtotal=$row1['subtotal'];
	$amountdue=$row1['amountdue'];
	$ddate=$row1['ddate'];
	$po_date=$row1['po_date'];
	$taxamount=$row1['taxamount'];
	$totalAftertax=$row1['totalAftertax'];
  }
    $html.= "<div style='position:relative; width:1024px;'>";
    $html.= "<div>";
    $result2 = mysql_query("SELECT * FROM  vendor_tbl where ven_id=" .$ven_id,$conn);
	if($row2= mysql_fetch_array($result2))
	 {
		$ven_id1 = $row2['ven_id'] ;
	    $ven_compname = $row2['ven_compname'] ;
	    $ven_add1=$row2['ven_add1'];
		$ven_add2=$row2['ven_add2'];
	    $ven_city=$row2['ven_city'];
		$ven_pincode=$row2['ven_pincode'];
		$ven_state=$row2['ven_state'];
		$ven_country=$row2['ven_country'];
		$ven_contactperson=$row2['ven_contactperson'];
		}
		else
		{
			echo "Error";
	    }
	  
		$result = mysql_query("SELECT * FROM project_details where project_id=" .$project_id,$conn);
	if($row= mysql_fetch_array($result))
	 {
	    $project_name = $row['project_name'] ;
	    $place=$row['place'];
		$tinno=$row['tinno'];
	    $cstno=$row['cstno'];
		$address=$row['address'];
		$contactname=$row['contactname'];
		$mobilno=$row['mobilno'];
		$payment=$row['payment'];
			
		}
		else
		{
			echo "Error";
	 }

		$projectname = substr("$project_name", 6, 1);
$html.= "<div id='res' style='display:none'></div>";
$html.= "<b>F/PUR/SIS-PO/".$projectname."/".$po_no. "/". $curYear."-".$nexYear."</b><br />";
$html.=  "<div align='right'>" .$po_date. "<br /></div>";
$html.= "<b>To:</b><br />";
$html.=  $ven_compname. "<br />";
$html.=  $row2['ven_add1'] .", ".$row2['ven_add2']. ", <br/> ".$row2['ven_city']. "-".$row2['ven_pincode'];
$html.= "<center>";
$html.= " <b>Kind Attention: " .$ven_contactperson. "</b></center>";
$html.= "<b>Sub: Request for Delivery</b>";
$html.= "<b>Sub: PO for $po_no </b><br />";	
$html.=  "We are pleased to place the Purchase order as per the details mentioned below for our Project " ;
$html.=   "<b>" .$project_name. "</b>";
$html.= "&nbsp; the address and the contact person are mentioned below.";
$html.= "</div>";
$html.= "<div id='space'></div>";
$html.= "<table  cellpadding='0' cellspacing='0'  width='100%'  id='itemsTable' border='1' >";
$html.= "<tr>";
$html.= "<th><input type='checkbox' id='check_all' class='case' /><label for='check_all'></label></th>";
$html.= "<th><b>Code</b></th>";
$html.= "<th><b>width</b></th>";
$html.= "<th><b>height</b></th>";
$html.= "<th><b>unit</b></th>";
$html.= "<th><b>type</b></th>";
$html.= "<th colspan='2'><b>Material Cost</b></th>";
$html.= "<th colspan='2'><b>Installation Cost</b></th>";
$html.= "<th><b>Amount</b></th>";
$html.=  "</tr>";
$html.= "<tr>";
$html.= "<th></th>";
$html.= "<th>&nbsp;</th>";
$html.= "<th></th>";
$html.= "<th></th>";
$html.= "<th></th>";
$html.= "<th></th>";
$html.= "<th><b>Basic</b></th>";
$html.=  "<th><b>Total</b></th>";
$html.= "<th><b>Basic</b></th>";
$html.= "<th><b>Total</b></th>";
$html.= "<th><b>Total</b></th>";
$html.= " </tr>";
$result_r = mysql_query("SELECT * FROM  purchaseorder_tbl where Po_no=" .$po_no,$conn);

while($row = mysql_fetch_array($result_r))
 {
	$productname = $row['product_name'] ;
	$product_qty=$row['product_qty'];
	$pro_height = $row['pro_height'];
	$pro_width = $row['pro_width'];
	$m_basic = $row['m_basic'];
	$m_total = $row['m_total'];
	$i_basic = $row['i_basic'];
	$i_total = $row['i_total'];
	$Amount = $row['Amount'];
	$product_code = $row['product_code'];
		$po_date = $row['po_date'];
		$productname=$row['product_name'];		
		$n+=1;
$html.= "<tr><td>".$n."</label></td>";
$html.= "<td><div class='input-field col s8'> ".$product_code."</div></td>";
$html.= "<td><div class='input-field col s8'>".$pro_width."</div></td>";
$html.=  "<td><div class='input-field col s8'>".$pro_height."</div></td>";
$html.= "<td><div class='input-field col s8'>".$product_qty."</div></td>";
$html.= "<td><div class='input-field col s8'>".$productname."</div></td>";
$html.=  "<td><div class='input-field col s8'>".$m_basic."</div></td>";
$html.= "<td><div class='input-field col s8'>".$m_total."</div></td>";
$html.= "<td><div class='input-field col s8'>".$i_basic."</div></td>";
$html.= "<td><div class='input-field col s8'>".$i_total."</div></td>";
$html.= "<td><div class='input-field col s8'>".$Amount."</div></td>";
$html.= "</tr>";
 }
$html.= "<tr>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<td>BC</td>";
$html.= "<td><div class='input-field col s9'>".$basictotal."</td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "</tr>";
$html.= "<tr>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<td>ED</td>";
$html.= "<td><div class='input-field col s9'>".$ed."</div></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<th></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "</tr>";
$html.= "<tr>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<td>Vat</td>";
$html.= "<td><div class='input-field col s9'>".$tax."</div></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<th></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "</tr>";
$html.= "<tr>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<td>Transpotation</td>";
$html.= "<td><div class='input-field col s9'>".$transportation."</div></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<th></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "</tr>";
$html.= "<tr>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "<td>ST</td>";
$html.= "<td><div class='input-field col s9'>".$st."</div></td>";
$html.= "<td>&nbsp;</td>";
$html.= "<td></td>";
$html.= "<th></td>";
$html.= "<td></td>";
$html.= "<td></td>";
$html.= "</tr>";
$html.= "<tr>";	
$html.= "<td></td>";	
$html.= "<td></td>";	
$html.= "<td></td>";	
$html.= "<td></td>";	
$html.= "<td>Grand Total</td>";	
$html.= "<td><div class='input-field col s9'>".$gt."</div></td>";	
$html.= "<td>&nbsp;</td>";	
$html.= "<td>&nbsp;</td>";	
$html.= "<td>&nbsp;</td>";	
$html.= "<td class='cyan white-text'><div class='input-field col s9'>".$gt1."</div></td>";	
$html.= "<td class='cyan strong white-text'><div class='input-field col s9'>".$subtotal."</div></td>";	
$html.= "</tr>";
$html.= "</tbody>";	
$html.= "</table>";
$html.= "<div class='form-group'>";
$html.= "<label> &nbsp;</label>";
$html.= "<div class='input-group'>";
$html.= "<div align='right'>Total : Rs.".$subtotal. "</div>";
$html.= "</div></div><div>";
$html.= "<b>Term and Condition:</b><br />";
$html.= "<span class='pur_lbl'><label>Tin No</label> :" .$tinno. "<br />";	
$html.= "<span class='pur_lbl'><label>CST No</label>: </span>" .$cstno. "<br />";
$html.= "<span class='pur_lbl'><label>Payment</label> : </span>" .$payment. "<br />";  
$html.= "<span class='pur_lbl'>Delivery : </span>Door Dellivery to our" .$place. " Site  <br /> ";
$html.= "<span class='pur_lbl'>Loading & Vat :" .$vat_o. "<br />";
$html.= "<span class='pur_lbl'>Please Supply by " .$ddate. "at our ".$place. "Site<br />";
$html.= "The above price is net price inclusive of all Taxes and Transport Charges.The Other terms and conditions remains the same as per your Quote. <br />";
$html.= "<div style='width:100%;position:relative'><div style='width:30%;position:relative; float:left'><b>Site contact Person</b>  </div> ";
$html.=  "<div style='width:5%;position:relative; float:left'> <b>:</b></div><div style='width:30%;position:relative; float:left'><b>" .$contactname.  "</b></div><div style='width:5%;position:relative; float:left'> <b>:</b></div><div style='width:30%;position:relative; float:left'><b>" .$mobilno. "</b></div></div>";
$html.=  "<b>Site address : </b>";
$html.=   $project_name. "<br />";
$html.= "<div style='width:300px; padding-left:87px'>" .$address. "</br></div>" ;	
$html.= "</p>";
$html.= "Thanking you, <br />";
$html.= "Yours Sincerely<br />";
$html.= "<img src='images/anisa_digi.jpg' width='83' height='57' /><br />";
$html.= " Anisa Fathima.H <br />";
$html.= " Purchase Manager";
$html.= " <div>";
$html.= "</div>";
$html.= "</div>";
$html.= "</div>";
$mpdf->WriteHTML($html);
$mpdf->SetDisplayMode('fullpage');
$mpdf->Output("purchaseorder/PO-".$po_no.".pdf");
$file = "purchaseorder/PO-".$po_no.".pdf";
if (file_exists($file)) {
header('Content-Description: File Transfer');
header('Content-Type: application/octet-stream');
header('Content-Disposition: attachment; filename='.basename($file));
header('Content-Transfer-Encoding: binary');
header('Expires: 0');
header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
header('Pragma: public');
header('Content-Length: ' . filesize($file));
readfile($file);
unlink("purchaseorder/PO-".$po_no.".pdf");
exit;
} ?>